[colors.bright]
black = "#abb2bf"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#b48ead"
red = "#e06c75"
white = "#eceff4"
yellow = "#e5c07b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#61afef"
cyan = "#88c0d0"
green = "#98c379"
magenta = "#b48ead"
red = "#e06c75"
white = "#e5e9f0"
yellow = "#e5c07b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#abb2bf"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 10.0

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[window]
opacity = 0.85
